### ISSUE TITLE
How to install on Grub2win

### ISSUE THREAD

**Issue by Johnnyreyman** [vandalsoul/darkmatter-grub2-theme#11]
I would like to apply this theme to grub2win and I could not find the equivalent to /etc/default/grub. Here is a tree of the folder structure:
├───fonts
├───g2bootmgr
├───i386-efi
├───i386-pc
├───locale
├───themes
│   ├───backgrounds
│   ├───common
│   │   ├───clockfaces
│   │   ├───colorcustom
│   │   ├───colorsource
│   │   └───static
│   ├───dark-matter
│   │   └───icons
│   ├───icons
│   ├───master
│   ├───options.local
│   └───options.standard
├───userfiles
│   ├───user.backgrounds
│   ├───user.clockfaces
│   ├───user.fonts
│   ├───user.icons
│   └───user.misc.files
├───windata
│   ├───backups
│   │   ├───bcds
│   │   ├───logs
│   │   └───main
│   ├───commands
│   ├───customconfigs
│   ├───partdump
│   ├───storage
│   └───updatedata
├───winhelp
│   └───usermanual
│       ├───css
│       │   ├───dynatree
│       │   │   ├───chm
│       │   │   ├───folder
│       │   │   └───vista
│       │   └───silver-theme
│       │       └───images
│       ├───img
│       ├───js
│       └───lib
├───winsource
└───x86_64-efi

**Comment by vandalsoul** [comment]
Hey @Johnnyreyman I actually don't have any experience using `grub2win` so I can't help you right now, but I will check into it and let you know if I find the solution for this.
