### ISSUE TITLE
Blank screen, no GRUB!

### ISSUE THREAD

**Issue by ninjapika** [vandalsoul/darkmatter-grub2-theme#13]
I'm using Xubuntu 20.04 os. I tried to install dark matter grub theme using both auto install.py and manual install, but while booting; it shows my manufacturer's logo and just a blank screen and boots into the os after waiting for 5 secs(as specified in the grub timeout). I tried changing the theme styles, but same result for all. Here's my grub file at /etc/default

> GRUB_THEME="/boot/grub/themes/dark-matter/theme.txt"
GRUB_DEFAULT="0"
GRUB_TIMEOUT_STYLE="hidden"
GRUB_TIMEOUT="5"
GRUB_DISTRIBUTOR="lsb_release -i -s 2> /dev/null || echo Debian"
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
GRUB_CMDLINE_LINUX=""

Let me know if I have to provide any other info.

**Comment by vandalsoul** [comment]
Hey there @ninjapika 

Edit the file `/etc/default/grub`
First you should comment out **GRUB_TIMEOUT_STYLE** like `#GRUB_TIMEOUT_STYLE="hidden"`
Then if you have the line **GRUB_TERMINAL** uncommented, then comment it out as well and **Save** the file

Now open a terminal and update grub using,
```shell
sudo grub-mkconfig -o /boot/grub/grub.cfg
```
Hope this helps you out 😇

**Comment by ninjapika** [comment]
Thanks for your fix @vandalsoul, it worked.

:)
