### ISSUE TITLE
Multiple resolutions support

### ISSUE THREAD

**Issue by RicArch97** [vandalsoul/darkmatter-grub2-theme#22]
Looking at the backgrounds that currently exist, they are all 1080p.

I think it might be a good idea to create versions for the following resolutions, to make your theme widely available;

|Class|Resolution|
|:------:|:--------:|
|1080p|1920 x 1080|
|Ultrawide 1080p|2560 x 1080|
|1440p|2560 x 1440|
|Ultrawide 1440p|3440 x 1440|
|4K|3840 x 2160|

For ultrawide, there's extra space on the sides (21:9 aspect ratio) so you'll have to shift the items accordingly.

**Comment by vandalsoul** [comment]
Hi @RicArch97 
The main reason for this is because of the lack of availability of hardware for testing purposes and I'm planning to release a 2K version in the next v2.0 update along with the updated 1080p version
