### ISSUE TITLE
Theme Not Loading at 1080p In Slackware 15.0 & Grub 2.06

### ISSUE THREAD

**Issue by 0pLuS0** [vandalsoul/darkmatter-grub2-theme#23]
Hello,

Since installing Slackware 15.0, which was recently released, this is the second grub2 theme I have tried and both won't load at the native resolution of 1920x1080, they both show up at 1024x768.

I didn't have a problem running grub2 themes in Slackware 14.2, so I'm not sure what is going on different in Slackware 15.0 effecting this.

I ran the installer; ```python3 install.py``` and everything installed ok, no problems. There was, however one issue, ```GRUB_GFXMODE=1920x1080,auto``` was added 3 times to my /etc/default/grub, besides the line I had in there, which made 4 lines in total, so I hope you can correct this in a future update.

I'm attaching a copy of the /etc/default/grub, I'm lost, I have no idea why this won't show up at 1080p, and grub shows support for 1920x1080x32 when I check the supported resolutions in grub.

[grub.txt](https://github.com/vandalsoul/darkmatter-grub2-theme/files/8238845/grub.txt)

**Comment by vandalsoul** [comment]
Usually grub sets the resolution when you install a distro
My screen resolution is 1366x768 and I have the line `GRUB_GFXMODE=1024x768` in my grub file as default which is weird but it works fine, theme comes up in full screen

>There was, however one issue, GRUB_GFXMODE=1920x1080,auto was added 3 times to my /etc/default/grub, besides the line I had in there, which made 4 lines in total, so I hope you can correct this in a future update.

Cause of the above mentioned reason none of my install scripts actually add or change that line so it might have caused from one of the other themes you tried to install

> both won't load at the native resolution of 1920x1080, they both show up at 1024x768
I didn't have a problem running grub2 themes in Slackware 14.2, so I'm not sure what is going on different in Slackware 15.0 effecting this.

I actually don't know why it's happening but I'll see if I can find anything about it, I'm assuming you are not using a VM then it's completely normal

Also this is my grub file you can comment out the differences in yours and see if it works for you
https://pastebin.com/raw/L6sifsum

And if you can maybe try reinstalling grub, to see if it works, If you haven't done it before then first try reinstalling grub in a VM to avoid crashing

**Comment by vandalsoul** [comment]
Hi @0pLuS0 

Usually grub sets the resolution when you install a distro
My screen resolution is 1366x768 and I have the line `GRUB_GFXMODE=1024x768` in my grub file as default which is weird but it works fine, theme comes up in full screen

>There was, however one issue, GRUB_GFXMODE=1920x1080,auto was added 3 times to my /etc/default/grub, besides the line I had in there, which made 4 lines in total, so I hope you can correct this in a future update.

Cause of the above mentioned reason none of my install scripts actually add or change that line so it might have caused from one of the other themes you tried to install

> both won't load at the native resolution of 1920x1080, they both show up at 1024x768
I didn't have a problem running grub2 themes in Slackware 14.2, so I'm not sure what is going on different in Slackware 15.0 effecting this.

I actually don't know why it's happening but I'll see if I can find anything about it, I'm assuming you are not using a VM then it's completely normal

Also this is my grub file you can comment out the differences in yours and see if it works for you
https://pastebin.com/raw/L6sifsum

And if you can maybe try reinstalling grub, to see if it works, If you haven't done it before then first try reinstalling grub in a VM to avoid crashing

**Comment by 0pLuS0** [comment]
The script added the 3 lines as I mentioned, they weren't there before I ran it.

I'm not running a VM.

I reinstalled grub, if you mean, as; ```grub-install /dev/sda``` I did this already.

I don't see anything different in your grub config that would make a difference.

**Comment by 0pLuS0** [comment]
Ok on the 3 lines...

It just looks like 1024x768 resolution, it's more blown up, that's all, nothing really to see.

Has anything changed with grub or X that there are dependencies needed to make this work? Every time I install Slackware, I do an expert install and pick and chooose packages, but afterwards I run an LDD script that checks the system against what I have installed and will tell me if those pkgs are missing anything. As of this moment, I have nothing missing in my system, so that is why I also don't get why this won't work.

Hmm

**Comment by 0pLuS0** [comment]
Is there a way to debug grub to fiind out why it won't load at theme at my resoultion?

Thanks

**Comment by vandalsoul** [comment]
Hi @0pLuS0 

> Has anything changed with grub or X that there are dependencies needed to make this work?

None that I'm aware of actually

> Is there a way to debug grub to find out why it won't load at theme at my resolution?

You can check out grub [command-line](https://www.gnu.org/software/grub/manual/grub/grub.html#Command_002dline-and-menu-entry-commands) commands if you want for that, I don't have any experience with debugging grub so..

Anyway, I will try to recreate this issue by installing Slackware ( *haven't used it before* ).
I currently don't have any free hardware disk to install it, so might take a few days and I will post the updates here.

**Comment by 0pLuS0** [comment]
Well I didn't do a full install of Slack, so if you do get it working, then I'm missing something, but for the life of me, I can't understand what would be missing that would effect something like this.

I've used grub for a very long time in Slack, and this version of Slack is the first time I've run into this... hmm

**Comment by 0pLuS0** [comment]
I got it working!

I had to uncomment this line;

# Font used on the graphical terminal:
GRUB_FONT=/usr/share/grub/dejavusansmono.pf2

**Comment by vandalsoul** [comment]
@0pLuS0 
Oh that's awesome, it was actually commented out in that grub.txt you send earlier and yeah you don't need that line, theme's fonts are usually mentioned in theme.txt

**Comment by 0pLuS0** [comment]
So grub shouldn't need to have GRUB_FONT uncommented?

These should come from the themes fonts instead?

Hmm
