### ISSUE TITLE
Support for Avix linux

### ISSUE THREAD

**Issue by udarae2000** [vandalsoul/darkmatter-grub2-theme#27]
Hello I am an Avix Linux Developer and our distro is still under development and we want to know if you can help us with making a grub menu theme for the os . The icon is down below. The theme colors are white and blue like Arch Linux. Around 50 people are involved in this project and we are planning on having Dark Matter as the default theme. You will be credited for the grub theme on our website if you want. We would really appreciate it if you could help us out. - the Avix community

![avixfinal](https://user-images.githubusercontent.com/98133612/167785267-87fdc6cb-9b32-4e09-957f-285bda0a614c.png)

**Comment by Freerunnerlinux** [comment]
Hi i'm one of the main devs on this project, @udarae2000 is one of them as well . Our project is done by the *Nixified Community which is rebranding soon. My username online happens to be Dark Matter as well. 😄 Anyways here is the invite to the Discord server @vandalsoul  - https://discord.gg/dFBnH3JeEW

**Comment by Freerunnerlinux** [comment]
Also i'm commenting from an old github account with defunct notifications so just ping me if you have issues joining the server.

**Comment by vandalsoul** [comment]
Yup got it

Also I'm closing this issue for now.
