### ISSUE TITLE
Theme Style Request : Endeavour OS

### ISSUE THREAD

**Issue by maxlefou** [vandalsoul/darkmatter-grub2-theme#3]
(edited. I just noticed you prefer requests rather than giving graphic sources to help contributing)

Would love to see an endeavour os background for this gorgeous theme. Thanks ^^

**Comment by vandalsoul** [comment]
Hey @maxlefou I just added EndeavourOS style. Check it out !!

**Comment by maxlefou** [comment]
Beautiful! Time to install it ^^
